### ISSUE TITLE
Could not find artifact com.sun:tools:jar:1.8

### ISSUE THREAD

**Issue by maxiko** [rhuss/jolokia#473]
I'm tryng to run my app with embedded jolokia server. And i have an error
```Could not find artifact com.sun:tools:jar:1.8 at specified path```

My pom.xml
```            
            <dependency>
                <groupId>org.jolokia</groupId>
                <artifactId>jolokia-core</artifactId>
                <version>1.7.0</version>
            </dependency>
            <dependency>
                <groupId>org.jolokia</groupId>
                <artifactId>jolokia-spring</artifactId>
                <version>1.7.0</version>
            </dependency>
```

java --version output

```java 11.0.6 2020-01-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.6+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.6+8-LTS, mixed mode)
```

**Comment by rhuss** [comment]
Ah, good find @tadayosi . In the source pom.xml this looks like in https://github.com/rhuss/jolokia/blob/12e67893483f7d99f9fbe12bd4b6972e28e5d5a1/agent/jvm/pom.xml#L180-L194 but it seems that during the release the resolved pom is used. In 1.6.2 everything still looks ok --> https://repo1.maven.org/maven2/org/jolokia/jolokia-jvm/1.6.2/jolokia-jvm-1.6.2.pom

Excluding might help, but then you will not be able to attach dynamically to a running JVM anymore. I also wonder how one would extend this to newer JVMs 9 and 11. @grgrzybek any idea how this could be extended or what caused the publishing of the effective pom.xml and not the original one like in 1.6.2 ?

**Comment by grgrzybek** [comment]
And it's only resolved in one place...
```xml
    <profile>
      <id>default-tools-1.8.jar</id>
      <dependencies>
        <dependency>
          <groupId>com.sun</groupId>
          <artifactId>tools</artifactId>
          <version>1.8</version>
          <scope>system</scope>
          <systemPath>/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/../lib/tools.jar</systemPath>
        </dependency>
      </dependencies>
    </profile>
    <profile>
      <id>default-tools-1.7.jar</id>
      <dependencies>
        <dependency>
          <groupId>com.sun</groupId>
          <artifactId>tools</artifactId>
          <version>1.7</version>
          <scope>system</scope>
          <systemPath>${java.home}/../lib/tools.jar</systemPath>
        </dependency>
      </dependencies>
    </profile>
```

really strange...

**Comment by rhuss** [comment]
> To be honest I have no idea why resolved (`${java.home}` property) POM was pushed to Maven Central... I never had such problem before ;) @rhuss if it's resolved in Maven Central it is probably also resolved in your `~/.m2/repository`...

Really strange. Unfortunately I can't check the repo anymore as I do a release always from a fresh local repo (`-Dmaven.repo.local=/tmp/repo`), so that's gone already.

**Comment by rhuss** [comment]
I will try to push a 1.7.1 over the weekend and analyse the issue. However that probably doesn't solve it for Java >=9 as the corresponding sections are missing there. @grgrzybek do you have an idea whether `com.sun.tools.attach.VirtualMachine` is available for Java 9+ and which dependency would need to be added (it was that tools.jar for Java <= 8).

On the other hand, as I think you already kind of reflective class lookup we might not even need this section anymore, so that we can get rid of this system dependencies in the pom.xml ? wdyt ?

**Comment by grgrzybek** [comment]
For JDK <= 8 we need `<system>` scoped dependency - you just have to find why we learned about your `java.home` directory path ;)

> we might not even need this section anymore

And that's true - in JDK9, `com.sun.tools.attach.VirtualMachine` is part of `$JAVA_HOME/jmods/jdk.attach.jmod` and [I've added special code section to handle custom images](https://github.com/rhuss/jolokia/blob/b30d76e9d7bdd3b9a97c857e82426ccd56616a7d/agent/jvm/src/main/java/org/jolokia/jvmagent/client/util/PlatformUtils.java#L45-L55), so no worries ;)

**Comment by rhuss** [comment]
@grgrzybek see the PR above which fixes the issue. @maxiko @tadayosi I'm going to create a 1.7.1 over the weekend.

**Comment by grgrzybek** [comment]
Ah - that's what this option is for ;)

**Comment by rhuss** [comment]
@grgrzybek @tadayosi @maxiko 1.7.1 has just been released and fixes this very issue.

**Comment by grgrzybek** [comment]
Thank you very much!
